name             'shipio'
maintainer       'Ship.io'
maintainer_email 'pivotal-shipio@googlegroups.com'
license          'MIT'
description      'ShipIO stuff'
long_description 'Stuff'
version          '0.1.0'
supports         'mac_os_x'
depends          'sprout-base'
depends          'homebrew'
